language: node_js
node_js:
  - "8"
os:
  # - linux
  - osx

cache:
  directories:
    - node_modules

env:
  - CODECOV_TOKEN="932bd39a-1bbf-43fc-a0e6-3f05f31ee61c"

script:
  - yarn test:coverage

# hooks
before_install:
  - yarn global add yarn@1.9.4 --network-timeout 100000
